
// G_TYPE_MAKE_FUNDAMENTAL
const G_TYPE_BOOLEAN = 5;
const G_TYPE_INT = 6;
const G_TYPE_INVALID = 0;
const G_TYPE_STRING = 16;
const NULL = null;
const TRUE = true;
const FALSE = false;

function xpm_template() {
/*
this.button_layout=O|HMC;
this.button_offset=3;
this.button_spacing=3;
this.maximized_offset=4;
this.title_vertical_offset_active=1;
this.title_vertical_offset_inactive=1;
this.active_text_color=#fcfcfc;
this.inactive_text_color=#f9fbfe;
this.shadow_delta_x=-4;
this.shadow_delta_y=-4;
*/

this.xpm = {};this.c = {};
    this.c.settings = [
        /* Do not change the order of the following parameters */
        ["active_text_color", NULL, G_TYPE_STRING, FALSE],
        ["inactive_text_color", NULL, G_TYPE_STRING, FALSE],
        ["active_text_shadow_color", NULL, G_TYPE_STRING, FALSE],
        ["inactive_text_shadow_color", NULL, G_TYPE_STRING, FALSE],
        ["active_border_color", NULL, G_TYPE_STRING, FALSE],
        ["inactive_border_color", NULL, G_TYPE_STRING, FALSE],
        ["active_color_1", NULL, G_TYPE_STRING, FALSE],
        ["active_hilight_1", NULL, G_TYPE_STRING, FALSE],
        ["active_shadow_1", NULL, G_TYPE_STRING, FALSE],
        ["active_mid_1", NULL, G_TYPE_STRING, FALSE],
        ["active_text_color_2", NULL, G_TYPE_STRING, FALSE],
        ["active_color_2", NULL, G_TYPE_STRING, FALSE],
        ["active_hilight_2", NULL, G_TYPE_STRING, FALSE],
        ["active_shadow_2", NULL, G_TYPE_STRING, FALSE],
        ["active_mid_2", NULL, G_TYPE_STRING, FALSE],
        ["inactive_color_1", NULL, G_TYPE_STRING, FALSE],
        ["inactive_hilight_1", NULL, G_TYPE_STRING, FALSE],
        ["inactive_shadow_1", NULL, G_TYPE_STRING, FALSE],
        ["inactive_mid_1", NULL, G_TYPE_STRING, FALSE],
        ["inactive_text_color_2", NULL, G_TYPE_STRING, FALSE],
        ["inactive_color_2", NULL, G_TYPE_STRING, FALSE],
        ["inactive_hilight_2", NULL, G_TYPE_STRING, FALSE],
        ["inactive_shadow_2", NULL, G_TYPE_STRING, FALSE],
        ["inactive_mid_2", NULL, G_TYPE_STRING, FALSE],
        /* You can change the order of the following parameters */
        ["activate_action", NULL, G_TYPE_STRING, TRUE],
        ["borderless_maximize", NULL, G_TYPE_BOOLEAN, TRUE],
        ["box_move", NULL, G_TYPE_BOOLEAN, TRUE],
        ["box_resize", NULL, G_TYPE_BOOLEAN, TRUE],
        ["button_layout", NULL, G_TYPE_STRING, TRUE],
        ["button_offset", NULL, G_TYPE_INT, TRUE],
        ["button_spacing", NULL, G_TYPE_INT, TRUE],
        ["click_to_focus", NULL, G_TYPE_BOOLEAN, TRUE],
        ["cycle_apps_only", NULL, G_TYPE_BOOLEAN, TRUE],
        ["cycle_draw_frame", NULL, G_TYPE_BOOLEAN, TRUE],
        ["cycle_hidden", NULL, G_TYPE_BOOLEAN, TRUE],
        ["cycle_minimum", NULL, G_TYPE_BOOLEAN, TRUE],
        ["cycle_preview", NULL, G_TYPE_BOOLEAN, TRUE],
        ["cycle_tabwin_mode", NULL, G_TYPE_INT, FALSE],
        ["cycle_workspaces", NULL, G_TYPE_BOOLEAN, TRUE],
        ["double_click_action", NULL, G_TYPE_STRING, TRUE],
        ["double_click_distance", NULL, G_TYPE_INT, TRUE],
        ["double_click_time", NULL, G_TYPE_INT, TRUE],
        ["easy_click", NULL, G_TYPE_STRING, TRUE],
        ["focus_delay", NULL, G_TYPE_INT, TRUE],
        ["focus_hint", NULL, G_TYPE_BOOLEAN, TRUE],
        ["focus_new", NULL, G_TYPE_BOOLEAN,TRUE],
        ["frame_opacity", NULL, G_TYPE_INT, TRUE],
        ["full_width_title", NULL, G_TYPE_BOOLEAN, TRUE],
        ["horiz_scroll_opacity", NULL, G_TYPE_BOOLEAN, FALSE],
        ["inactive_opacity", NULL, G_TYPE_INT, TRUE],
        ["margin_bottom", NULL, G_TYPE_INT, FALSE],
        ["margin_left", NULL, G_TYPE_INT, FALSE],
        ["margin_right", NULL, G_TYPE_INT, FALSE],
        ["margin_top", NULL, G_TYPE_INT, FALSE],
        ["maximized_offset", NULL, G_TYPE_INT, TRUE],
        ["mousewheel_rollup", NULL, G_TYPE_BOOLEAN, FALSE],
        ["move_opacity", NULL, G_TYPE_INT, TRUE],
        ["placement_mode", NULL, G_TYPE_STRING, TRUE],
        ["placement_ratio", NULL, G_TYPE_INT, TRUE],
        ["popup_opacity", NULL, G_TYPE_INT, TRUE],
        ["prevent_focus_stealing", NULL, G_TYPE_BOOLEAN, TRUE],
        ["raise_delay", NULL, G_TYPE_INT, TRUE],
        ["raise_on_click", NULL, G_TYPE_BOOLEAN, TRUE],
        ["raise_on_focus", NULL, G_TYPE_BOOLEAN, TRUE],
        ["raise_with_any_button", NULL, G_TYPE_BOOLEAN, TRUE],
        ["repeat_urgent_blink", NULL, G_TYPE_BOOLEAN, TRUE],
        ["resize_opacity", NULL, G_TYPE_INT, TRUE],
        ["scroll_workspaces", NULL, G_TYPE_BOOLEAN, TRUE],
        ["shadow_delta_height", NULL, G_TYPE_INT, TRUE],
        ["shadow_delta_width", NULL, G_TYPE_INT, TRUE],
        ["shadow_delta_x", NULL, G_TYPE_INT, TRUE],
        ["shadow_delta_y", NULL, G_TYPE_INT, TRUE],
        ["shadow_opacity", NULL, G_TYPE_INT, TRUE],
        ["show_app_icon", NULL, G_TYPE_BOOLEAN, TRUE],
        ["show_dock_shadow", NULL, G_TYPE_BOOLEAN, TRUE],
        ["show_frame_shadow", NULL, G_TYPE_BOOLEAN, TRUE],
        ["show_popup_shadow", NULL, G_TYPE_BOOLEAN, TRUE],
        ["snap_resist", NULL, G_TYPE_BOOLEAN, TRUE],
        ["snap_to_border", NULL, G_TYPE_BOOLEAN, TRUE],
        ["snap_to_windows", NULL, G_TYPE_BOOLEAN, TRUE],
        ["snap_width", NULL, G_TYPE_INT, TRUE],
        ["sync_to_vblank", NULL, G_TYPE_BOOLEAN, TRUE],
        ["theme", NULL, G_TYPE_STRING, TRUE],
        ["tile_on_move", NULL, G_TYPE_BOOLEAN, TRUE],
        ["title_alignment", NULL, G_TYPE_STRING, TRUE],
        ["title_font", NULL, G_TYPE_STRING, FALSE],
        ["title_horizontal_offset", NULL, G_TYPE_INT, TRUE],
        ["titleless_maximize", NULL, G_TYPE_BOOLEAN, TRUE],
        ["title_shadow_active", NULL, G_TYPE_STRING, TRUE],
        ["title_shadow_inactive", NULL, G_TYPE_STRING, TRUE],
        ["title_vertical_offset_active", NULL, G_TYPE_INT, TRUE],
        ["title_vertical_offset_inactive", NULL, G_TYPE_INT, TRUE],
        ["toggle_workspaces", NULL, G_TYPE_BOOLEAN, TRUE],
        ["unredirect_overlays", NULL, G_TYPE_BOOLEAN, TRUE],
        ["urgent_blink", NULL, G_TYPE_BOOLEAN, TRUE],
        ["use_compositing", NULL, G_TYPE_BOOLEAN, TRUE],
        ["workspace_count", NULL, G_TYPE_INT, TRUE],
        ["wrap_cycle", NULL, G_TYPE_BOOLEAN, TRUE],
        ["wrap_layout", NULL, G_TYPE_BOOLEAN, TRUE],
        ["wrap_resistance", NULL, G_TYPE_INT, TRUE],
        ["wrap_windows", NULL, G_TYPE_BOOLEAN, TRUE],
        ["wrap_workspaces", NULL, G_TYPE_BOOLEAN, TRUE],
        ["zoom_desktop", NULL, G_TYPE_BOOLEAN, TRUE],
        [NULL, NULL, G_TYPE_INVALID, FALSE]
    ];
this.xpm.bottom_active = [
"4 3 3 1",
" 	c None",
".	c #EEEEEE",
"+	c #6F88B1",
"....",
"....",
"++++"];
this.xpm.bottom_active = [
"4 3 2 1",
".	c #F0F0F0",
"+	c #9fb0ca",
"....",
"....",
"++++"];
this.xpm.bottom_left_active = [
"3 3 4 1",
" 	c None",
".	c #6F88B1",
"+	c #EEEEEE",
"@	c #A4B1CA",
".++",
" .+",
"  ."];
this.xpm.bottom_left_inactive = [
"3 3 4 1",
" 	c None",
".	c #9FB0CA",
"+	c #F0F0F0",
"@	c #CDD3DF",
".++",
" .+",
"  ."];
this.xpm.bottom_right_active = [
"3 3 4 1",
" 	c None",
".	c #EEEEEE",
"+	c #6F88B1",
"@	c #A4B1CA",
"..+",
".+ ",
"+  "];
this.xpm.bottom_right_inactive = [
"3 3 4 1",
" 	c None",
".	c #F0F0F0",
"+	c #9FB0CA",
"@	c #CDD3DF",
"..+",
".+ ",
"+  "];
this.xpm.close_active = [
"16 16 11 1",
" 	c None",
".	c #6980A7",
"+	c #6782AF",
"@	c #6781AD",
"#	c #6680AC",
"$	c #6982AB",
"%	c #6680AA",
"&	c #C6D0E0",
"*	c #6780A9",
"=	c #677FA7",
"-	c #687FA6",
"................",
"++++++++++++++++",
"++++++++++++++++",
"@@@@@@@@@@@@@@@@",
"################",
"###$$$$$$$$$####",
"%%%$&&$$$&&$%%%%",
"***$&&&$&&&$****",
"===$$&&&&&$$====",
"---$$$&&&$$$----",
"===$$&&&&&$$====",
"***$&&&$&&&$****",
"%%%$&&$$$&&$%%%%",
"###$$$$$$$$$####",
"################",
"@@@@@@@@@@@@@@@@"];
this.xpm.close_inactive = [
"16 16 6 1",
" 	c None",
".	c #CED3DC",
"+	c #CDD3DF",
"@	c #CED4DE",
"#	c #CDD3DD",
"$	c #E9ECF0",
"................",
"++++++++++++++++",
"@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@",
"################",
"...#########....",
"...#$$###$$#....",
"...#$$$#$$$#....",
"...##$$$$$##....",
"...###$$$###....",
"...##$$$$$##....",
"...#$$$#$$$#....",
"...#$$###$$#....",
"...#########....",
"################",
"@@@@@@@@@@@@@@@@"];
this.xpm.close_pressed = [
"16 16 12 1",
" 	c None",
".	c #6980A7",
"+	c #6783B1",
"@	c #6883B0",
"#	c #6882AE",
"$	c #6881AC",
"%	c #6982AB",
"&	c #6888BE",
"*	c #6781AB",
"=	c #C2DCFC",
"-	c #6981A9",
";	c #6880A8",
"................",
"++++++++++++++++",
"@@@@@@@@@@@@@@@@",
"################",
"$$$$$$$$$$$$$$$$",
"%%%&&&&&&&&&%%%%",
"***&==&&&==&****",
"---&===&===&----",
";;;&&=====&&;;;;",
"...&&&===&&&....",
";;;&&=====&&;;;;",
"---&===&===&----",
"***&==&&&==&****",
"%%%&&&&&&&&&%%%%",
"$$$$$$$$$$$$$$$$",
"################"];
this.xpm.hide_active = [
"16 16 11 1",
" 	c None",
".	c #6980A7",
"+	c #6782AF",
"@	c #6781AD",
"#	c #6680AC",
"$	c #6982AB",
"%	c #6680AA",
"&	c #6780A9",
"*	c #677FA7",
"=	c #687FA6",
"-	c #C6D0E0",
"................",
"++++++++++++++++",
"++++++++++++++++",
"@@@@@@@@@@@@@@@@",
"################",
"####$$$$$$$$$###",
"%%%%$$$$$$$$$%%%",
"&&&&$$$$$$$$$&&&",
"****$$$$$$$$$***",
"====$-------$===",
"****$-------$***",
"&&&&$$$$$$$$$&&&",
"%%%%$$$$$$$$$%%%",
"####$$$$$$$$$###",
"################",
"@@@@@@@@@@@@@@@@"];
this.xpm.hide_inactive = [
"16 16 6 1",
" 	c None",
".	c #CED3DC",
"+	c #CDD3DF",
"@	c #CED4DE",
"#	c #CDD3DD",
"$	c #E9ECF0",
"................",
"++++++++++++++++",
"@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@",
"################",
"....#########...",
"....#########...",
"....#########...",
"....#########...",
"....#$$$$$$$#...",
"....#$$$$$$$#...",
"....#########...",
"....#########...",
"....#########...",
"################",
"@@@@@@@@@@@@@@@@"];
this.xpm.hide_pressed = [
"16 16 12 1",
" 	c None",
".	c #6980A7",
"+	c #6783B1",
"@	c #6883B0",
"#	c #6882AE",
"$	c #6881AC",
"%	c #6982AB",
"&	c #6888BE",
"*	c #6781AB",
"=	c #6981A9",
"-	c #6880A8",
";	c #C2DCFC",
"................",
"++++++++++++++++",
"@@@@@@@@@@@@@@@@",
"################",
"$$$$$$$$$$$$$$$$",
"%%%%&&&&&&&&&%%%",
"****&&&&&&&&&***",
"====&&&&&&&&&===",
"----&&&&&&&&&---",
"....&;;;;;;;&...",
"----&;;;;;;;&---",
"====&&&&&&&&&===",
"****&&&&&&&&&***",
"%%%%&&&&&&&&&%%%",
"$$$$$$$$$$$$$$$$",
"################"];
this.xpm.left_active = [
"3 4 2 1",
".	c #6F88B1",
"+	c #EEEEEE",
".++",
".++",
".++",
".++"];
this.xpm.left_active = [
"3 4 2 1",
".	c #9fb0ca",
"+	c #F0F0F0",
".++",
".++",
".++",
".++"];
this.xpm.maximize_active = [
"16 16 11 1",
" 	c None",
".	c #6980A7",
"+	c #6782AF",
"@	c #6781AD",
"#	c #6680AC",
"$	c #6982AB",
"%	c #6680AA",
"&	c #6780A9",
"*	c #C6D0E0",
"=	c #677FA7",
"-	c #687FA6",
"................",
"++++++++++++++++",
"++++++++++++++++",
"@@@@@@@@@@@@@@@@",
"################",
"####$$$$$$$$$###",
"%%%%$$$$$$$$$%%%",
"&&&&$$$$*$$$$&&&",
"====$$$***$$$===",
"----$$*****$$---",
"====$***$***$===",
"&&&&$**$$$**$&&&",
"%%%%$$$$$$$$$%%%",
"####$$$$$$$$$###",
"################",
"@@@@@@@@@@@@@@@@"];
this.xpm.maximize_inactive = [
"16 16 6 1",
" 	c None",
".	c #CED3DC",
"+	c #CDD3DF",
"@	c #CED4DE",
"#	c #CDD3DD",
"$	c #E9ECF0",
"................",
"++++++++++++++++",
"@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@",
"################",
"....#########...",
"....#########...",
"....####$####...",
"....###$$$###...",
"....##$$$$$##...",
"....#$$$#$$$#...",
"....#$$###$$#...",
"....#########...",
"....#########...",
"################",
"@@@@@@@@@@@@@@@@"];
this.xpm.maximize_pressed = [
"16 16 12 1",
" 	c None",
".	c #6980A7",
"+	c #6783B1",
"@	c #6883B0",
"#	c #6882AE",
"$	c #6881AC",
"%	c #6982AB",
"&	c #6888BE",
"*	c #6781AB",
"=	c #6981A9",
"-	c #C2DCFC",
";	c #6880A8",
"................",
"++++++++++++++++",
"@@@@@@@@@@@@@@@@",
"################",
"$$$$$$$$$$$$$$$$",
"%%%%&&&&&&&&&%%%",
"****&&&&&&&&&***",
"====&&&&-&&&&===",
";;;;&&&---&&&;;;",
"....&&-----&&...",
";;;;&---&---&;;;",
"====&--&&&--&===",
"****&&&&&&&&&***",
"%%%%&&&&&&&&&%%%",
"$$$$$$$$$$$$$$$$",
"################"];
this.xpm.maximize_toggled_active = [
"16 16 11 1",
" 	c None",
".	c #6980A7",
"+	c #6782AF",
"@	c #6781AD",
"#	c #6680AC",
"$	c #6982AB",
"%	c #6680AA",
"&	c #6780A9",
"*	c #677FA7",
"=	c #C6D0E0",
"-	c #687FA6",
"................",
"++++++++++++++++",
"++++++++++++++++",
"@@@@@@@@@@@@@@@@",
"################",
"####$$$$$$$$$###",
"%%%%$$$$$$$$$%%%",
"&&&&$$$$$$$$$&&&",
"****$==$$$==$***",
"----$===$===$---",
"****$$=====$$***",
"&&&&$$$===$$$&&&",
"%%%%$$$$=$$$$%%%",
"####$$$$$$$$$###",
"################",
"@@@@@@@@@@@@@@@@"];
this.xpm.maximize_toggled_inactive = [
"16 16 6 1",
" 	c None",
".	c #CED3DC",
"+	c #CDD3DF",
"@	c #CED4DE",
"#	c #CDD3DD",
"$	c #E9ECF0",
"................",
"++++++++++++++++",
"@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@",
"################",
"....#########...",
"....#########...",
"....#########...",
"....#$$###$$#...",
"....#$$$#$$$#...",
"....##$$$$$##...",
"....###$$$###...",
"....####$####...",
"....#########...",
"################",
"@@@@@@@@@@@@@@@@"];
this.xpm.maximize_toggled_pressed = [
"16 16 12 1",
" 	c None",
".	c #6980A7",
"+	c #6783B1",
"@	c #6883B0",
"#	c #6882AE",
"$	c #6881AC",
"%	c #6982AB",
"&	c #6888BE",
"*	c #6781AB",
"=	c #6981A9",
"-	c #6880A8",
";	c #C2DCFC",
"................",
"++++++++++++++++",
"@@@@@@@@@@@@@@@@",
"################",
"$$$$$$$$$$$$$$$$",
"%%%%&&&&&&&&&%%%",
"****&&&&&&&&&***",
"====&&&&&&&&&===",
"----&;;&&&;;&---",
"....&;;;&;;;&...",
"----&&;;;;;&&---",
"====&&&;;;&&&===",
"****&&&&;&&&&***",
"%%%%&&&&&&&&&%%%",
"$$$$$$$$$$$$$$$$",
"################"];
this.xpm.menu_active = [
"16 16 11 1",
" 	c None",
".	c #6980A7",
"+	c #6782AF",
"@	c #6781AD",
"#	c #6680AC",
"$	c #6982AB",
"%	c #6680AA",
"&	c #6780A9",
"*	c #C6D0E0",
"=	c #677FA7",
"-	c #687FA6",
"................",
"++++++++++++++++",
"++++++++++++++++",
"@@@@@@@@@@@@@@@@",
"################",
"####$$$$$$$$$###",
"%%%%$$$$$$$$$%%%",
"&&&&$$$***$$$&&&",
"====$$*****$$===",
"----$$*****$$---",
"====$$*****$$===",
"&&&&$$$***$$$&&&",
"%%%%$$$$$$$$$%%%",
"####$$$$$$$$$###",
"################",
"@@@@@@@@@@@@@@@@"];
this.xpm.menu_inactive = [
"16 16 6 1",
" 	c None",
".	c #CED3DC",
"+	c #CDD3DF",
"@	c #CED4DE",
"#	c #CDD3DD",
"$	c #E9ECF0",
"................",
"++++++++++++++++",
"@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@",
"################",
"....#########...",
"....#########...",
"....###$$$###...",
"....##$$$$$##...",
"....##$$$$$##...",
"....##$$$$$##...",
"....###$$$###...",
"....#########...",
"....#########...",
"################",
"@@@@@@@@@@@@@@@@"];
this.xpm.menu_pressed = [
"16 16 11 1",
" 	c None",
".	c #677FA7",
"+	c #6A84B0",
"@	c #6B84AF",
"#	c #6983AF",
"$	c #6983AD",
"%	c #6982AB",
"&	c #6888BE",
"*	c #6781AB",
"=	c #6981A9",
"-	c #C2DCFC",
"................",
"++++++++++++++++",
"@@@@@@@@@@@@@@@@",
"################",
"$$$$$$$$$$$$$$$$",
"%%%%&&&&&&&&&%%%",
"****&&&&&&&&&***",
"====&&&---&&&===",
"....&&-----&&...",
"....&&-----&&...",
"....&&-----&&...",
"====&&&---&&&===",
"****&&&&&&&&&***",
"%%%%&&&&&&&&&%%%",
"$$$$$$$$$$$$$$$$",
"################"];
this.xpm.right_active = [
"3 4 2 1",
".	c #EEEEEE",
"+	c #6F88B1",
"..+",
"..+",
"..+",
"..+"];
this.xpm.right_active = [
"3 4 2 1",
".	c #F0F0F0",
"+	c #9fb0ca",
"..+",
"..+",
"..+",
"..+"];
this.xpm.title_active = [
"4 22 10 1",
" 	c None",
".	c #6F88B1",
"+	c #EEEEEE",
"@	c #687FA6",
"#	c #6782AF",
"$	c #6781AD",
"%	c #6680AC",
"&	c #6680AA",
"*	c #6780A9",
"=	c #677FA7",
"....",
"++++",
"++++",
"@@@@",
"####",
"####",
"$$$$",
"%%%%",
"%%%%",
"&&&&",
"****",
"====",
"@@@@",
"====",
"****",
"&&&&",
"%%%%",
"%%%%",
"$$$$",
"####",
"####",
"@@@@"];
this.xpm.title_inactive = [
"3 22 6 1",
".	c #A0B2CA",
"+	c #F0F0F0",
"@	c #CED3DC",
"#	c #CDD3DF",
"$	c #CED4DE",
"%	c #CDD3DD",
"...",
"+++",
"+++",
"@@@",
"###",
"$$$",
"$$$",
"%%%",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"%%%",
"$$$",
"$$$",
"###",
"@@@"];
this.xpm.title_active = [
"4 22 10 1",
" 	c None",
".	c #6F88B1",
"+	c #EEEEEE",
"@	c #687FA6",
"#	c #6782AF",
"$	c #6781AD",
"%	c #6680AC",
"&	c #6680AA",
"*	c #6780A9",
"=	c #677FA7",
"....",
"++++",
"++++",
"@@@@",
"####",
"####",
"$$$$",
"%%%%",
"%%%%",
"&&&&",
"****",
"====",
"@@@@",
"====",
"****",
"&&&&",
"%%%%",
"%%%%",
"$$$$",
"####",
"####",
"@@@@"];
this.xpm.title_inactive = [
"3 22 6 1",
".	c #A0B2CA",
"+	c #F0F0F0",
"@	c #CED3DC",
"#	c #CDD3DF",
"$	c #CED4DE",
"%	c #CDD3DD",
"...",
"+++",
"+++",
"@@@",
"###",
"$$$",
"$$$",
"%%%",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"%%%",
"$$$",
"$$$",
"###",
"@@@"];
this.xpm.title_active = [
"4 22 10 1",
" 	c None",
".	c #6F88B1",
"+	c #EEEEEE",
"@	c #687FA6",
"#	c #6782AF",
"$	c #6781AD",
"%	c #6680AC",
"&	c #6680AA",
"*	c #6780A9",
"=	c #677FA7",
"....",
"++++",
"++++",
"@@@@",
"####",
"####",
"$$$$",
"%%%%",
"%%%%",
"&&&&",
"****",
"====",
"@@@@",
"====",
"****",
"&&&&",
"%%%%",
"%%%%",
"$$$$",
"####",
"####",
"@@@@"];
this.xpm.title_inactive = [
"3 22 6 1",
".	c #A0B2CA",
"+	c #F0F0F0",
"@	c #CED3DC",
"#	c #CDD3DF",
"$	c #CED4DE",
"%	c #CDD3DD",
"...",
"+++",
"+++",
"@@@",
"###",
"$$$",
"$$$",
"%%%",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"%%%",
"$$$",
"$$$",
"###",
"@@@"];
this.xpm.title_active = [
"4 22 10 1",
" 	c None",
".	c #6F88B1",
"+	c #EEEEEE",
"@	c #687FA6",
"#	c #6782AF",
"$	c #6781AD",
"%	c #6680AC",
"&	c #6680AA",
"*	c #6780A9",
"=	c #677FA7",
"....",
"++++",
"++++",
"@@@@",
"####",
"####",
"$$$$",
"%%%%",
"%%%%",
"&&&&",
"****",
"====",
"@@@@",
"====",
"****",
"&&&&",
"%%%%",
"%%%%",
"$$$$",
"####",
"####",
"@@@@"];
this.xpm.title_inactive = [
"3 22 6 1",
".	c #A0B2CA",
"+	c #F0F0F0",
"@	c #CED3DC",
"#	c #CDD3DF",
"$	c #CED4DE",
"%	c #CDD3DD",
"...",
"+++",
"+++",
"@@@",
"###",
"$$$",
"$$$",
"%%%",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"%%%",
"$$$",
"$$$",
"###",
"@@@"];
this.xpm.title_active = [
"4 22 10 1",
" 	c None",
".	c #6F88B1",
"+	c #EEEEEE",
"@	c #687FA6",
"#	c #6782AF",
"$	c #6781AD",
"%	c #6680AC",
"&	c #6680AA",
"*	c #6780A9",
"=	c #677FA7",
"....",
"++++",
"++++",
"@@@@",
"####",
"####",
"$$$$",
"%%%%",
"%%%%",
"&&&&",
"****",
"====",
"@@@@",
"====",
"****",
"&&&&",
"%%%%",
"%%%%",
"$$$$",
"####",
"####",
"@@@@"];
this.xpm.title_inactive = [
"3 22 6 1",
".	c #A0B2CA",
"+	c #F0F0F0",
"@	c #CED3DC",
"#	c #CDD3DF",
"$	c #CED4DE",
"%	c #CDD3DD",
"...",
"+++",
"+++",
"@@@",
"###",
"$$$",
"$$$",
"%%%",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"@@@",
"%%%",
"$$$",
"$$$",
"###",
"@@@"];
this.xpm.top_left_active = [
"4 22 5 1",
" 	c None",
".	c #6F88B1",
"+	c #EEEEEE",
"@	c #A4B2CA",
"#	c #687FA6",
"  ..",
" .++",
".+++",
".++@",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++@"];
this.xpm.top_left_inactive = [
"4 22 5 1",
" 	c None",
".	c #A0B2CA",
"+	c #F0F0F0",
"@	c #CDD3DF",
"#	c #CED3DC",
"  ..",
" .++",
".+++",
".++@",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++#",
".++@"];
this.xpm.top_right_active = [
"4 22 5 1",
" 	c None",
".	c #6F88B1",
"+	c #EEEEEE",
"@	c #A4B2CA",
"#	c #687FA6",
"..  ",
"++. ",
"+++.",
"@++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"@++."];
this.xpm.top_right_inactive = [
"4 22 5 1",
" 	c None",
".	c #A0B2CA",
"+	c #F0F0F0",
"@	c #CDD3DF",
"#	c #CED3DC",
"..  ",
"++. ",
"+++.",
"@++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"#++.",
"@++."];
}

var theme = new xpm_template();

Object.keys(theme.xpm).forEach(function (element){
        let xpm = get_xpm_data(element);
        console.log(element, xpm.width, xpm.height, xpm.colors, xpm.cpp);
});

// returns width, height obj
function get_xpm_data(data) {
  let row = theme.xpm[data][0].split(" ");
  let width = parseInt(row[0]);
  let height = parseInt(row[1]);
  let colors = parseInt(row[2]);
  let cpp = parseInt(row[3])
  let ctable = theme.xpm[data].slice(1,colors+1);
  let pixels = theme.xpm[data].slice(colors+1);
  return {width: width, height: height, colors: colors, cpp: cpp, ctable: ctable, pixels:pixels};
}




/*
List of decoration part names.

| menu-active         | menu-inactive         | menu-prelight     | menu-pressed     |                         |                           |                           |                          |
| shade-active        | shade-inactive        | shade-prelight    | shade-pressed    | shade-toggled-active    | shade-toggled-inactive    | shade-toggled-prelight    | shade-toggled-pressed    |
| stick-active        | stick-inactive        | stick-prelight    | stick-pressed    | stick-toggled-active    | stick-toggled-inactive    | stick-toggled-prelight    | stick-toggled-pressed    |
| hide-active         | hide-inactive         | hide-prelight     | hide-pressed     |                         |                           |                           |                          |
| maximize-active     | maximize-inactive     | maximize-prelight | maximize-pressed | maximize-toggled-active | maximize-toggled-inactive | maximize-toggled-prelight | maximize-toggled-pressed |
| close-active        | close-inactive        | close-prelight    | close-pressed    |                         |                           |                           |                          |
| top-left-active     | top-left-inactive     |                   |                  |                         |                           |                           |                          |
| title-1-active      | title-1-inactive      |                   |                  |                         |                           |                           |                          |
| title-2-active      | title-2-inactive      |                   |                  |                         |                           |                           |                          |
| title-3-active      | title-3-inactive      |                   |                  |                         |                           |                           |                          |
| title-4-active      | title-4-inactive      |                   |                  |                         |                           |                           |                          |
| title-5-active      | title-5-inactive      |                   |                  |                         |                           |                           |                          |
| top-right-active    | top-right-inactive    |                   |                  |                         |                           |                           |                          |
| right-active        | right-inactive        |                   |                  |                         |                           |                           |                          |
| bottom-right-active | bottom-right-inactive |                   |                  |                         |                           |                           |                          |
| bottom-active       | bottom-inactive       |                   |                  |                         |                           |                           |                          |
| bottom-left-active  | bottom-left-inactive  |                   |                  |                         |                           |                           |                          |
| left-active         | left-inactive         |                   |                  |                         |                           |                           |                          |
*/

