// G_TYPE_MAKE_FUNDAMENTAL
const G_TYPE_BOOLEAN = 5;
const G_TYPE_INT = 6;
const G_TYPE_INVALID = 0;
const G_TYPE_STRING = 16;
const NULL = null;
const TRUE = true;
const FALSE = false;

function xpm_template() {

    this.button_layout = "O|HMC";
    this.button_offset = 3;
    this.button_spacing = 3;
    this.maximized_offset = 4;
    this.title_vertical_offset_active = 1;
    this.title_vertical_offset_inactive = 1;
    this.active_text_color = "#fcfcfc";
    this.inactive_text_color = "#f9fbfe";
    this.shadow_delta_x = -4;
    this.shadow_delta_y = -4;

    this.settings_rc = [
        /* Do not change the order of the following parameters */
        ["active_text_color", NULL, G_TYPE_STRING, FALSE],
        ["inactive_text_color", NULL, G_TYPE_STRING, FALSE],
        ["active_text_shadow_color", NULL, G_TYPE_STRING, FALSE],
        ["inactive_text_shadow_color", NULL, G_TYPE_STRING, FALSE],
        ["active_border_color", NULL, G_TYPE_STRING, FALSE],
        ["inactive_border_color", NULL, G_TYPE_STRING, FALSE],
        ["active_color_1", NULL, G_TYPE_STRING, FALSE],
        ["active_hilight_1", NULL, G_TYPE_STRING, FALSE],
        ["active_shadow_1", NULL, G_TYPE_STRING, FALSE],
        ["active_mid_1", NULL, G_TYPE_STRING, FALSE],
        ["active_text_color_2", NULL, G_TYPE_STRING, FALSE],
        ["active_color_2", NULL, G_TYPE_STRING, FALSE],
        ["active_hilight_2", NULL, G_TYPE_STRING, FALSE],
        ["active_shadow_2", NULL, G_TYPE_STRING, FALSE],
        ["active_mid_2", NULL, G_TYPE_STRING, FALSE],
        ["inactive_color_1", NULL, G_TYPE_STRING, FALSE],
        ["inactive_hilight_1", NULL, G_TYPE_STRING, FALSE],
        ["inactive_shadow_1", NULL, G_TYPE_STRING, FALSE],
        ["inactive_mid_1", NULL, G_TYPE_STRING, FALSE],
        ["inactive_text_color_2", NULL, G_TYPE_STRING, FALSE],
        ["inactive_color_2", NULL, G_TYPE_STRING, FALSE],
        ["inactive_hilight_2", NULL, G_TYPE_STRING, FALSE],
        ["inactive_shadow_2", NULL, G_TYPE_STRING, FALSE],
        ["inactive_mid_2", NULL, G_TYPE_STRING, FALSE],
        /* You can change the order of the following parameters */
        ["activate_action", NULL, G_TYPE_STRING, TRUE],
        ["borderless_maximize", NULL, G_TYPE_BOOLEAN, TRUE],
        ["box_move", NULL, G_TYPE_BOOLEAN, TRUE],
        ["box_resize", NULL, G_TYPE_BOOLEAN, TRUE],
        ["button_layout", NULL, G_TYPE_STRING, TRUE],
        ["button_offset", NULL, G_TYPE_INT, TRUE],
        ["button_spacing", NULL, G_TYPE_INT, TRUE],
        ["click_to_focus", NULL, G_TYPE_BOOLEAN, TRUE],
        ["cycle_apps_only", NULL, G_TYPE_BOOLEAN, TRUE],
        ["cycle_draw_frame", NULL, G_TYPE_BOOLEAN, TRUE],
        ["cycle_hidden", NULL, G_TYPE_BOOLEAN, TRUE],
        ["cycle_minimum", NULL, G_TYPE_BOOLEAN, TRUE],
        ["cycle_preview", NULL, G_TYPE_BOOLEAN, TRUE],
        ["cycle_tabwin_mode", NULL, G_TYPE_INT, FALSE],
        ["cycle_workspaces", NULL, G_TYPE_BOOLEAN, TRUE],
        ["double_click_action", NULL, G_TYPE_STRING, TRUE],
        ["double_click_distance", NULL, G_TYPE_INT, TRUE],
        ["double_click_time", NULL, G_TYPE_INT, TRUE],
        ["easy_click", NULL, G_TYPE_STRING, TRUE],
        ["focus_delay", NULL, G_TYPE_INT, TRUE],
        ["focus_hint", NULL, G_TYPE_BOOLEAN, TRUE],
        ["focus_new", NULL, G_TYPE_BOOLEAN, TRUE],
        ["frame_opacity", NULL, G_TYPE_INT, TRUE],
        ["full_width_title", NULL, G_TYPE_BOOLEAN, TRUE],
        ["horiz_scroll_opacity", NULL, G_TYPE_BOOLEAN, FALSE],
        ["inactive_opacity", NULL, G_TYPE_INT, TRUE],
        ["margin_bottom", NULL, G_TYPE_INT, FALSE],
        ["margin_left", NULL, G_TYPE_INT, FALSE],
        ["margin_right", NULL, G_TYPE_INT, FALSE],
        ["margin_top", NULL, G_TYPE_INT, FALSE],
        ["maximized_offset", NULL, G_TYPE_INT, TRUE],
        ["mousewheel_rollup", NULL, G_TYPE_BOOLEAN, FALSE],
        ["move_opacity", NULL, G_TYPE_INT, TRUE],
        ["placement_mode", NULL, G_TYPE_STRING, TRUE],
        ["placement_ratio", NULL, G_TYPE_INT, TRUE],
        ["popup_opacity", NULL, G_TYPE_INT, TRUE],
        ["prevent_focus_stealing", NULL, G_TYPE_BOOLEAN, TRUE],
        ["raise_delay", NULL, G_TYPE_INT, TRUE],
        ["raise_on_click", NULL, G_TYPE_BOOLEAN, TRUE],
        ["raise_on_focus", NULL, G_TYPE_BOOLEAN, TRUE],
        ["raise_with_any_button", NULL, G_TYPE_BOOLEAN, TRUE],
        ["repeat_urgent_blink", NULL, G_TYPE_BOOLEAN, TRUE],
        ["resize_opacity", NULL, G_TYPE_INT, TRUE],
        ["scroll_workspaces", NULL, G_TYPE_BOOLEAN, TRUE],
        ["shadow_delta_height", NULL, G_TYPE_INT, TRUE],
        ["shadow_delta_width", NULL, G_TYPE_INT, TRUE],
        ["shadow_delta_x", NULL, G_TYPE_INT, TRUE],
        ["shadow_delta_y", NULL, G_TYPE_INT, TRUE],
        ["shadow_opacity", NULL, G_TYPE_INT, TRUE],
        ["show_app_icon", NULL, G_TYPE_BOOLEAN, TRUE],
        ["show_dock_shadow", NULL, G_TYPE_BOOLEAN, TRUE],
        ["show_frame_shadow", NULL, G_TYPE_BOOLEAN, TRUE],
        ["show_popup_shadow", NULL, G_TYPE_BOOLEAN, TRUE],
        ["snap_resist", NULL, G_TYPE_BOOLEAN, TRUE],
        ["snap_to_border", NULL, G_TYPE_BOOLEAN, TRUE],
        ["snap_to_windows", NULL, G_TYPE_BOOLEAN, TRUE],
        ["snap_width", NULL, G_TYPE_INT, TRUE],
        ["sync_to_vblank", NULL, G_TYPE_BOOLEAN, TRUE],
        ["theme", NULL, G_TYPE_STRING, TRUE],
        ["tile_on_move", NULL, G_TYPE_BOOLEAN, TRUE],
        ["title_alignment", NULL, G_TYPE_STRING, TRUE],
        ["title_font", NULL, G_TYPE_STRING, FALSE],
        ["title_horizontal_offset", NULL, G_TYPE_INT, TRUE],
        ["titleless_maximize", NULL, G_TYPE_BOOLEAN, TRUE],
        ["title_shadow_active", NULL, G_TYPE_STRING, TRUE],
        ["title_shadow_inactive", NULL, G_TYPE_STRING, TRUE],
        ["title_vertical_offset_active", NULL, G_TYPE_INT, TRUE],
        ["title_vertical_offset_inactive", NULL, G_TYPE_INT, TRUE],
        ["toggle_workspaces", NULL, G_TYPE_BOOLEAN, TRUE],
        ["unredirect_overlays", NULL, G_TYPE_BOOLEAN, TRUE],
        ["urgent_blink", NULL, G_TYPE_BOOLEAN, TRUE],
        ["use_compositing", NULL, G_TYPE_BOOLEAN, TRUE],
        ["workspace_count", NULL, G_TYPE_INT, TRUE],
        ["wrap_cycle", NULL, G_TYPE_BOOLEAN, TRUE],
        ["wrap_layout", NULL, G_TYPE_BOOLEAN, TRUE],
        ["wrap_resistance", NULL, G_TYPE_INT, TRUE],
        ["wrap_windows", NULL, G_TYPE_BOOLEAN, TRUE],
        ["wrap_workspaces", NULL, G_TYPE_BOOLEAN, TRUE],
        ["zoom_desktop", NULL, G_TYPE_BOOLEAN, TRUE],
        [NULL, NULL, G_TYPE_INVALID, FALSE]
    ];
    this.bottom_active = [
        "4 3 3 1",
        " 	c None",
        ".	c #EEEEEE",
        "+	c #6F88B1",
        "....",
        "....",
        "++++"
    ];
    this.bottom_active = [
        "4 3 2 1",
        ".	c #F0F0F0",
        "+	c #9fb0ca",
        "....",
        "....",
        "++++"
    ];
    this.bottom_left_active = [
        "3 3 4 1",
        " 	c None",
        ".	c #6F88B1",
        "+	c #EEEEEE",
        "@	c #A4B1CA",
        ".++",
        " .+",
        "  ."
    ];
    this.bottom_left_inactive = [
        "3 3 4 1",
        " 	c None",
        ".	c #9FB0CA",
        "+	c #F0F0F0",
        "@	c #CDD3DF",
        ".++",
        " .+",
        "  ."
    ];
    this.bottom_right_active = [
        "3 3 4 1",
        " 	c None",
        ".	c #EEEEEE",
        "+	c #6F88B1",
        "@	c #A4B1CA",
        "..+",
        ".+ ",
        "+  "
    ];
    this.bottom_right_inactive = [
        "3 3 4 1",
        " 	c None",
        ".	c #F0F0F0",
        "+	c #9FB0CA",
        "@	c #CDD3DF",
        "..+",
        ".+ ",
        "+  "
    ];
    this.close_active = [
        "16 16 11 1",
        " 	c None",
        ".	c #6980A7",
        "+	c #6782AF",
        "@	c #6781AD",
        "#	c #6680AC",
        "$	c #6982AB",
        "%	c #6680AA",
        "&	c #C6D0E0",
        "*	c #6780A9",
        "=	c #677FA7",
        "-	c #687FA6",
        "................",
        "++++++++++++++++",
        "++++++++++++++++",
        "@@@@@@@@@@@@@@@@",
        "################",
        "###$$$$$$$$$####",
        "%%%$&&$$$&&$%%%%",
        "***$&&&$&&&$****",
        "===$$&&&&&$$====",
        "---$$$&&&$$$----",
        "===$$&&&&&$$====",
        "***$&&&$&&&$****",
        "%%%$&&$$$&&$%%%%",
        "###$$$$$$$$$####",
        "################",
        "@@@@@@@@@@@@@@@@"
    ];
    this.close_inactive = [
        "16 16 6 1",
        " 	c None",
        ".	c #CED3DC",
        "+	c #CDD3DF",
        "@	c #CED4DE",
        "#	c #CDD3DD",
        "$	c #E9ECF0",
        "................",
        "++++++++++++++++",
        "@@@@@@@@@@@@@@@@",
        "@@@@@@@@@@@@@@@@",
        "################",
        "...#########....",
        "...#$$###$$#....",
        "...#$$$#$$$#....",
        "...##$$$$$##....",
        "...###$$$###....",
        "...##$$$$$##....",
        "...#$$$#$$$#....",
        "...#$$###$$#....",
        "...#########....",
        "################",
        "@@@@@@@@@@@@@@@@"
    ];
    this.close_pressed = [
        "16 16 12 1",
        " 	c None",
        ".	c #6980A7",
        "+	c #6783B1",
        "@	c #6883B0",
        "#	c #6882AE",
        "$	c #6881AC",
        "%	c #6982AB",
        "&	c #6888BE",
        "*	c #6781AB",
        "=	c #C2DCFC",
        "-	c #6981A9",
        ";	c #6880A8",
        "................",
        "++++++++++++++++",
        "@@@@@@@@@@@@@@@@",
        "################",
        "$$$$$$$$$$$$$$$$",
        "%%%&&&&&&&&&%%%%",
        "***&==&&&==&****",
        "---&===&===&----",
        ";;;&&=====&&;;;;",
        "...&&&===&&&....",
        ";;;&&=====&&;;;;",
        "---&===&===&----",
        "***&==&&&==&****",
        "%%%&&&&&&&&&%%%%",
        "$$$$$$$$$$$$$$$$",
        "################"
    ];
    this.hide_active = [
        "16 16 11 1",
        " 	c None",
        ".	c #6980A7",
        "+	c #6782AF",
        "@	c #6781AD",
        "#	c #6680AC",
        "$	c #6982AB",
        "%	c #6680AA",
        "&	c #6780A9",
        "*	c #677FA7",
        "=	c #687FA6",
        "-	c #C6D0E0",
        "................",
        "++++++++++++++++",
        "++++++++++++++++",
        "@@@@@@@@@@@@@@@@",
        "################",
        "####$$$$$$$$$###",
        "%%%%$$$$$$$$$%%%",
        "&&&&$$$$$$$$$&&&",
        "****$$$$$$$$$***",
        "====$-------$===",
        "****$-------$***",
        "&&&&$$$$$$$$$&&&",
        "%%%%$$$$$$$$$%%%",
        "####$$$$$$$$$###",
        "################",
        "@@@@@@@@@@@@@@@@"
    ];
    this.hide_inactive = [
        "16 16 6 1",
        " 	c None",
        ".	c #CED3DC",
        "+	c #CDD3DF",
        "@	c #CED4DE",
        "#	c #CDD3DD",
        "$	c #E9ECF0",
        "................",
        "++++++++++++++++",
        "@@@@@@@@@@@@@@@@",
        "@@@@@@@@@@@@@@@@",
        "################",
        "....#########...",
        "....#########...",
        "....#########...",
        "....#########...",
        "....#$$$$$$$#...",
        "....#$$$$$$$#...",
        "....#########...",
        "....#########...",
        "....#########...",
        "################",
        "@@@@@@@@@@@@@@@@"
    ];
    this.hide_pressed = [
        "16 16 12 1",
        " 	c None",
        ".	c #6980A7",
        "+	c #6783B1",
        "@	c #6883B0",
        "#	c #6882AE",
        "$	c #6881AC",
        "%	c #6982AB",
        "&	c #6888BE",
        "*	c #6781AB",
        "=	c #6981A9",
        "-	c #6880A8",
        ";	c #C2DCFC",
        "................",
        "++++++++++++++++",
        "@@@@@@@@@@@@@@@@",
        "################",
        "$$$$$$$$$$$$$$$$",
        "%%%%&&&&&&&&&%%%",
        "****&&&&&&&&&***",
        "====&&&&&&&&&===",
        "----&&&&&&&&&---",
        "....&;;;;;;;&...",
        "----&;;;;;;;&---",
        "====&&&&&&&&&===",
        "****&&&&&&&&&***",
        "%%%%&&&&&&&&&%%%",
        "$$$$$$$$$$$$$$$$",
        "################"
    ];
    this.left_active = [
        "3 4 2 1",
        ".	c #6F88B1",
        "+	c #EEEEEE",
        ".++",
        ".++",
        ".++",
        ".++"
    ];
    this.left_active = [
        "3 4 2 1",
        ".	c #9fb0ca",
        "+	c #F0F0F0",
        ".++",
        ".++",
        ".++",
        ".++"
    ];
    this.maximize_active = [
        "16 16 11 1",
        " 	c None",
        ".	c #6980A7",
        "+	c #6782AF",
        "@	c #6781AD",
        "#	c #6680AC",
        "$	c #6982AB",
        "%	c #6680AA",
        "&	c #6780A9",
        "*	c #C6D0E0",
        "=	c #677FA7",
        "-	c #687FA6",
        "................",
        "++++++++++++++++",
        "++++++++++++++++",
        "@@@@@@@@@@@@@@@@",
        "################",
        "####$$$$$$$$$###",
        "%%%%$$$$$$$$$%%%",
        "&&&&$$$$*$$$$&&&",
        "====$$$***$$$===",
        "----$$*****$$---",
        "====$***$***$===",
        "&&&&$**$$$**$&&&",
        "%%%%$$$$$$$$$%%%",
        "####$$$$$$$$$###",
        "################",
        "@@@@@@@@@@@@@@@@"
    ];
    this.maximize_inactive = [
        "16 16 6 1",
        " 	c None",
        ".	c #CED3DC",
        "+	c #CDD3DF",
        "@	c #CED4DE",
        "#	c #CDD3DD",
        "$	c #E9ECF0",
        "................",
        "++++++++++++++++",
        "@@@@@@@@@@@@@@@@",
        "@@@@@@@@@@@@@@@@",
        "################",
        "....#########...",
        "....#########...",
        "....####$####...",
        "....###$$$###...",
        "....##$$$$$##...",
        "....#$$$#$$$#...",
        "....#$$###$$#...",
        "....#########...",
        "....#########...",
        "################",
        "@@@@@@@@@@@@@@@@"
    ];
    this.maximize_pressed = [
        "16 16 12 1",
        " 	c None",
        ".	c #6980A7",
        "+	c #6783B1",
        "@	c #6883B0",
        "#	c #6882AE",
        "$	c #6881AC",
        "%	c #6982AB",
        "&	c #6888BE",
        "*	c #6781AB",
        "=	c #6981A9",
        "-	c #C2DCFC",
        ";	c #6880A8",
        "................",
        "++++++++++++++++",
        "@@@@@@@@@@@@@@@@",
        "################",
        "$$$$$$$$$$$$$$$$",
        "%%%%&&&&&&&&&%%%",
        "****&&&&&&&&&***",
        "====&&&&-&&&&===",
        ";;;;&&&---&&&;;;",
        "....&&-----&&...",
        ";;;;&---&---&;;;",
        "====&--&&&--&===",
        "****&&&&&&&&&***",
        "%%%%&&&&&&&&&%%%",
        "$$$$$$$$$$$$$$$$",
        "################"
    ];
    this.maximize_toggled_active = [
        "16 16 11 1",
        " 	c None",
        ".	c #6980A7",
        "+	c #6782AF",
        "@	c #6781AD",
        "#	c #6680AC",
        "$	c #6982AB",
        "%	c #6680AA",
        "&	c #6780A9",
        "*	c #677FA7",
        "=	c #C6D0E0",
        "-	c #687FA6",
        "................",
        "++++++++++++++++",
        "++++++++++++++++",
        "@@@@@@@@@@@@@@@@",
        "################",
        "####$$$$$$$$$###",
        "%%%%$$$$$$$$$%%%",
        "&&&&$$$$$$$$$&&&",
        "****$==$$$==$***",
        "----$===$===$---",
        "****$$=====$$***",
        "&&&&$$$===$$$&&&",
        "%%%%$$$$=$$$$%%%",
        "####$$$$$$$$$###",
        "################",
        "@@@@@@@@@@@@@@@@"
    ];
    this.maximize_toggled_inactive = [
        "16 16 6 1",
        " 	c None",
        ".	c #CED3DC",
        "+	c #CDD3DF",
        "@	c #CED4DE",
        "#	c #CDD3DD",
        "$	c #E9ECF0",
        "................",
        "++++++++++++++++",
        "@@@@@@@@@@@@@@@@",
        "@@@@@@@@@@@@@@@@",
        "################",
        "....#########...",
        "....#########...",
        "....#########...",
        "....#$$###$$#...",
        "....#$$$#$$$#...",
        "....##$$$$$##...",
        "....###$$$###...",
        "....####$####...",
        "....#########...",
        "################",
        "@@@@@@@@@@@@@@@@"
    ];
    this.maximize_toggled_pressed = [
        "16 16 12 1",
        " 	c None",
        ".	c #6980A7",
        "+	c #6783B1",
        "@	c #6883B0",
        "#	c #6882AE",
        "$	c #6881AC",
        "%	c #6982AB",
        "&	c #6888BE",
        "*	c #6781AB",
        "=	c #6981A9",
        "-	c #6880A8",
        ";	c #C2DCFC",
        "................",
        "++++++++++++++++",
        "@@@@@@@@@@@@@@@@",
        "################",
        "$$$$$$$$$$$$$$$$",
        "%%%%&&&&&&&&&%%%",
        "****&&&&&&&&&***",
        "====&&&&&&&&&===",
        "----&;;&&&;;&---",
        "....&;;;&;;;&...",
        "----&&;;;;;&&---",
        "====&&&;;;&&&===",
        "****&&&&;&&&&***",
        "%%%%&&&&&&&&&%%%",
        "$$$$$$$$$$$$$$$$",
        "################"
    ];
    this.menu_active = [
        "16 16 11 1",
        " 	c None",
        ".	c #6980A7",
        "+	c #6782AF",
        "@	c #6781AD",
        "#	c #6680AC",
        "$	c #6982AB",
        "%	c #6680AA",
        "&	c #6780A9",
        "*	c #C6D0E0",
        "=	c #677FA7",
        "-	c #687FA6",
        "................",
        "++++++++++++++++",
        "++++++++++++++++",
        "@@@@@@@@@@@@@@@@",
        "################",
        "####$$$$$$$$$###",
        "%%%%$$$$$$$$$%%%",
        "&&&&$$$***$$$&&&",
        "====$$*****$$===",
        "----$$*****$$---",
        "====$$*****$$===",
        "&&&&$$$***$$$&&&",
        "%%%%$$$$$$$$$%%%",
        "####$$$$$$$$$###",
        "################",
        "@@@@@@@@@@@@@@@@"
    ];
    this.menu_inactive = [
        "16 16 6 1",
        " 	c None",
        ".	c #CED3DC",
        "+	c #CDD3DF",
        "@	c #CED4DE",
        "#	c #CDD3DD",
        "$	c #E9ECF0",
        "................",
        "++++++++++++++++",
        "@@@@@@@@@@@@@@@@",
        "@@@@@@@@@@@@@@@@",
        "################",
        "....#########...",
        "....#########...",
        "....###$$$###...",
        "....##$$$$$##...",
        "....##$$$$$##...",
        "....##$$$$$##...",
        "....###$$$###...",
        "....#########...",
        "....#########...",
        "################",
        "@@@@@@@@@@@@@@@@"
    ];
    this.menu_pressed = [
        "16 16 11 1",
        " 	c None",
        ".	c #677FA7",
        "+	c #6A84B0",
        "@	c #6B84AF",
        "#	c #6983AF",
        "$	c #6983AD",
        "%	c #6982AB",
        "&	c #6888BE",
        "*	c #6781AB",
        "=	c #6981A9",
        "-	c #C2DCFC",
        "................",
        "++++++++++++++++",
        "@@@@@@@@@@@@@@@@",
        "################",
        "$$$$$$$$$$$$$$$$",
        "%%%%&&&&&&&&&%%%",
        "****&&&&&&&&&***",
        "====&&&---&&&===",
        "....&&-----&&...",
        "....&&-----&&...",
        "....&&-----&&...",
        "====&&&---&&&===",
        "****&&&&&&&&&***",
        "%%%%&&&&&&&&&%%%",
        "$$$$$$$$$$$$$$$$",
        "################"
    ];
    this.right_active = [
        "3 4 2 1",
        ".	c #EEEEEE",
        "+	c #6F88B1",
        "..+",
        "..+",
        "..+",
        "..+"
    ];
    this.right_active = [
        "3 4 2 1",
        ".	c #F0F0F0",
        "+	c #9fb0ca",
        "..+",
        "..+",
        "..+",
        "..+"
    ];
    this.title_active = [
        "4 22 10 1",
        " 	c None",
        ".	c #6F88B1",
        "+	c #EEEEEE",
        "@	c #687FA6",
        "#	c #6782AF",
        "$	c #6781AD",
        "%	c #6680AC",
        "&	c #6680AA",
        "*	c #6780A9",
        "=	c #677FA7",
        "....",
        "++++",
        "++++",
        "@@@@",
        "####",
        "####",
        "$$$$",
        "%%%%",
        "%%%%",
        "&&&&",
        "****",
        "====",
        "@@@@",
        "====",
        "****",
        "&&&&",
        "%%%%",
        "%%%%",
        "$$$$",
        "####",
        "####",
        "@@@@"
    ];
    this.title_inactive = [
        "3 22 6 1",
        ".	c #A0B2CA",
        "+	c #F0F0F0",
        "@	c #CED3DC",
        "#	c #CDD3DF",
        "$	c #CED4DE",
        "%	c #CDD3DD",
        "...",
        "+++",
        "+++",
        "@@@",
        "###",
        "$$$",
        "$$$",
        "%%%",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "%%%",
        "$$$",
        "$$$",
        "###",
        "@@@"
    ];
    this.title_active = [
        "4 22 10 1",
        " 	c None",
        ".	c #6F88B1",
        "+	c #EEEEEE",
        "@	c #687FA6",
        "#	c #6782AF",
        "$	c #6781AD",
        "%	c #6680AC",
        "&	c #6680AA",
        "*	c #6780A9",
        "=	c #677FA7",
        "....",
        "++++",
        "++++",
        "@@@@",
        "####",
        "####",
        "$$$$",
        "%%%%",
        "%%%%",
        "&&&&",
        "****",
        "====",
        "@@@@",
        "====",
        "****",
        "&&&&",
        "%%%%",
        "%%%%",
        "$$$$",
        "####",
        "####",
        "@@@@"
    ];
    this.title_inactive = [
        "3 22 6 1",
        ".	c #A0B2CA",
        "+	c #F0F0F0",
        "@	c #CED3DC",
        "#	c #CDD3DF",
        "$	c #CED4DE",
        "%	c #CDD3DD",
        "...",
        "+++",
        "+++",
        "@@@",
        "###",
        "$$$",
        "$$$",
        "%%%",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "%%%",
        "$$$",
        "$$$",
        "###",
        "@@@"
    ];
    this.title_active = [
        "4 22 10 1",
        " 	c None",
        ".	c #6F88B1",
        "+	c #EEEEEE",
        "@	c #687FA6",
        "#	c #6782AF",
        "$	c #6781AD",
        "%	c #6680AC",
        "&	c #6680AA",
        "*	c #6780A9",
        "=	c #677FA7",
        "....",
        "++++",
        "++++",
        "@@@@",
        "####",
        "####",
        "$$$$",
        "%%%%",
        "%%%%",
        "&&&&",
        "****",
        "====",
        "@@@@",
        "====",
        "****",
        "&&&&",
        "%%%%",
        "%%%%",
        "$$$$",
        "####",
        "####",
        "@@@@"
    ];
    this.title_inactive = [
        "3 22 6 1",
        ".	c #A0B2CA",
        "+	c #F0F0F0",
        "@	c #CED3DC",
        "#	c #CDD3DF",
        "$	c #CED4DE",
        "%	c #CDD3DD",
        "...",
        "+++",
        "+++",
        "@@@",
        "###",
        "$$$",
        "$$$",
        "%%%",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "%%%",
        "$$$",
        "$$$",
        "###",
        "@@@"
    ];
    this.title_active = [
        "4 22 10 1",
        " 	c None",
        ".	c #6F88B1",
        "+	c #EEEEEE",
        "@	c #687FA6",
        "#	c #6782AF",
        "$	c #6781AD",
        "%	c #6680AC",
        "&	c #6680AA",
        "*	c #6780A9",
        "=	c #677FA7",
        "....",
        "++++",
        "++++",
        "@@@@",
        "####",
        "####",
        "$$$$",
        "%%%%",
        "%%%%",
        "&&&&",
        "****",
        "====",
        "@@@@",
        "====",
        "****",
        "&&&&",
        "%%%%",
        "%%%%",
        "$$$$",
        "####",
        "####",
        "@@@@"
    ];
    this.title_inactive = [
        "3 22 6 1",
        ".	c #A0B2CA",
        "+	c #F0F0F0",
        "@	c #CED3DC",
        "#	c #CDD3DF",
        "$	c #CED4DE",
        "%	c #CDD3DD",
        "...",
        "+++",
        "+++",
        "@@@",
        "###",
        "$$$",
        "$$$",
        "%%%",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "%%%",
        "$$$",
        "$$$",
        "###",
        "@@@"
    ];
    this.title_active = [
        "4 22 10 1",
        " 	c None",
        ".	c #6F88B1",
        "+	c #EEEEEE",
        "@	c #687FA6",
        "#	c #6782AF",
        "$	c #6781AD",
        "%	c #6680AC",
        "&	c #6680AA",
        "*	c #6780A9",
        "=	c #677FA7",
        "....",
        "++++",
        "++++",
        "@@@@",
        "####",
        "####",
        "$$$$",
        "%%%%",
        "%%%%",
        "&&&&",
        "****",
        "====",
        "@@@@",
        "====",
        "****",
        "&&&&",
        "%%%%",
        "%%%%",
        "$$$$",
        "####",
        "####",
        "@@@@"
    ];
    this.title_inactive = [
        "3 22 6 1",
        ".	c #A0B2CA",
        "+	c #F0F0F0",
        "@	c #CED3DC",
        "#	c #CDD3DF",
        "$	c #CED4DE",
        "%	c #CDD3DD",
        "...",
        "+++",
        "+++",
        "@@@",
        "###",
        "$$$",
        "$$$",
        "%%%",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "@@@",
        "%%%",
        "$$$",
        "$$$",
        "###",
        "@@@"
    ];
    this.top_left_active = [
        "4 22 5 1",
        " 	c None",
        ".	c #6F88B1",
        "+	c #EEEEEE",
        "@	c #A4B2CA",
        "#	c #687FA6",
        "  ..",
        " .++",
        ".+++",
        ".++@",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++@"
    ];
    this.top_left_inactive = [
        "4 22 5 1",
        " 	c None",
        ".	c #A0B2CA",
        "+	c #F0F0F0",
        "@	c #CDD3DF",
        "#	c #CED3DC",
        "  ..",
        " .++",
        ".+++",
        ".++@",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++#",
        ".++@"
    ];
    this.top_right_active = [
        "4 22 5 1",
        " 	c None",
        ".	c #6F88B1",
        "+	c #EEEEEE",
        "@	c #A4B2CA",
        "#	c #687FA6",
        "..  ",
        "++. ",
        "+++.",
        "@++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "@++."
    ];
    this.top_right_inactive = [
        "4 22 5 1",
        " 	c None",
        ".	c #A0B2CA",
        "+	c #F0F0F0",
        "@	c #CDD3DF",
        "#	c #CED3DC",
        "..  ",
        "++. ",
        "+++.",
        "@++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "#++.",
        "@++."
    ];
}